# Generated by Django 4.0.5 on 2024-03-05 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
                ('subject_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sydney_participant', models.CharField(max_length=20)),
                ('sydney_percentile', models.CharField(max_length=20)),
                ('correct_answer_percentage_per_class', models.IntegerField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('participant', models.CharField(max_length=50)),
                ('student_score', models.IntegerField()),
                ('year_level_name', models.CharField(max_length=20)),
                ('answer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.answer')),
                ('assessment_area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.assessmentarea')),
                ('award_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.award')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.category')),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.class')),
                ('correct_answer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.correctanswer')),
                ('school_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.school')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.student')),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.subject')),
            ],
        ),
    ]
