# Generated by Django 4.0.5 on 2024-03-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_category_id_alter_correctanswer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='participant',
            field=models.IntegerField(),
        ),
    ]
